# -*- coding: utf-8 -*-
{
    'name': 'Empleados',
    'version': '1.6',
    'author': 'SystemOuts',
    'website': '',
    'category': 'Localization PE/HR',
    'description': """Se agregan nuevas características de Empleados.""",
    'depends': [
        'hr',
        'base',
        'account',
        'l10n_latam_base',
        'hr_contracts',
        'hr_payroll',
        'mail',
        # 'hr_employee_portal',
        # 'mail_template_multi_attachment',
        # 'pc_l10n_pe_vat_sunat',
        'l10n_pe_vat_sunat',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/employee_layout_report.xml',
        'wizard/hr_coste_center_employee.xml',
        'reports/report.xml',
        'reports/report_dec_streets.xml',
        'reports/report_dec_no_5ta.xml',
        'reports/report_cargo_rit.xml',
        'reports/report_cargo_risst.xml',
        'reports/report_entry_form.xml',
        'views/comis_system.xml',
        'views/pension_system.xml',
        'views/health_regime.xml',
        'views/hr_employee_health.xml',
        'views/hr_employee_pension.xml',
        'views/hr_sctr.xml',
        'views/hr_table_localization.xml',
        'views/hr_job.xml',
        'views/res_bank.xml',
        'views/hr_employee.xml',
        # 'views/res_company.xml',
        'data/cron_hr_employee_age.xml',
        'data/template_new_employee.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
