{
    'name': 'Reportes en Nomina',
    'version': '1.0',
    'author': 'SystemOuts',
    'description': "",
    'depends': [
        'hr',
        'hr_afectations',
        'hr_payroll',
        'hr_contract',
        'l10n_latam_base',
        'hr_employees',
    ],
    'data': [
        'data/hr_employee_category_data.xml',
        'data/plame.lines.csv',
        'security/ir.model.access.csv',
        'views/afp_interface_views.xml',
        'views/base_views.xml',
        'views/payslip_interface_views.xml',
        'views/plame_files_views.xml',
        'views/plame_lines_views.xml',
        'views/annualized_interface_view.xml',
        'views/lbs_interface_views.xml',
        'views/afp_interface_reports.xml',
        'reports/report.xml',        
        'reports/report_afp_interface.xml', 
        'reports/report_plame_tax_settlement.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
