# -*- coding: utf-8 -*-
{
    "name": "Contabilidad - Tesoreria",
    "version": "1.0",
    "author": "SystemOuts",
    "category": "Accounting & Finance",
    "summary": "Modulo para la tesoreria, maneja las cuentas bancarias y realiza las operaciones como generar pagos, generar detracciones",
    "license": "LGPL-3",
    "depends": [
        "base",
        "account",
        "account_accountant",
        "account_purchases",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_rule.xml",
        "views/acc_detrac_mass_line.xml",
        "views/acc_detrac_mass.xml",
        "views/acc_payment_mass_views.xml",
        # 'views/account_canal_views.xml',
        # 'views/account_move_views.xml',
        # 'views/account_pendings_views.xml',
        # 'views/account_zonal_views.xml',
        # 'views/expense_concept.xml',
        # 'views/expense_type.xml',
        "views/res_partner_bank_views.xml",
        "views/txt_file_save_views.xml",
        "views/acc_menu_views.xml",
    ],
    "installable": True,
    'application': True,
    "auto_install": False,
    "sequence": -1,
}
